import type { GuiSearchEnvelope } from "./types";

export const mockSearchEnvelope: GuiSearchEnvelope = {
  ok: true,
  response: {
    result_count: 2,
    warnings: [],
    rendered: [
      {
        rank: 1,
        total_price_cny: 7438,
        outbound: {
          itinerary: "PVG(上海浦东国际机场) -> MNL(马尼拉尼诺伊·阿基诺国际机场) -> MEL(墨尔本机场)",
          segments: [
            {
              route: "PVG(上海浦东国际机场) -> MNL(马尼拉尼诺伊·阿基诺国际机场)",
              flight_number: "5J679",
              airline: "Cebu Pacific",
              airline_zh: "宿务太平洋航空",
              aircraft: "Airbus A320neo",
              aircraft_zh: "空客 A320neo",
              origin_airport: "PVG",
              origin_airport_name_zh: "上海浦东国际机场",
              departure_time: "2026-09-29T01:35:00",
              destination_airport: "MNL",
              destination_airport_name_zh: "马尼拉尼诺伊·阿基诺国际机场",
              arrival_time: "2026-09-29T05:35:00",
            },
            {
              route: "MNL(马尼拉尼诺伊·阿基诺国际机场) -> MEL(墨尔本机场)",
              flight_number: "5J49",
              airline: "Cebu Pacific",
              airline_zh: "宿务太平洋航空",
              aircraft: "Airbus A330-900neo",
              aircraft_zh: "空客 A330-900neo",
              origin_airport: "MNL",
              origin_airport_name_zh: "马尼拉尼诺伊·阿基诺国际机场",
              departure_time: "2026-09-29T12:55:00",
              destination_airport: "MEL",
              destination_airport_name_zh: "墨尔本机场",
              arrival_time: "2026-09-29T23:10:00",
            },
          ],
          segment_summaries: [],
          stop_count: 1,
          layovers: [{ airport: "MNL", airport_name_zh: "马尼拉尼诺伊·阿基诺国际机场", duration_hours: 7.3 }],
          stop_layover_summary: "1 次中转；MNL(马尼拉尼诺伊·阿基诺国际机场) 停留 7.3 小时",
          price_cny: 3478,
          airlines: ["宿务太平洋航空"],
          departure_time: "2026-09-29T01:35:00",
          arrival_time: "2026-09-29T23:10:00",
          origin_airport: "PVG",
          destination_airport: "MEL",
          layover_hours_total: 7.3,
          layover_cities: ["MNL(马尼拉尼诺伊·阿基诺国际机场)"],
        },
        inbound: {
          itinerary: "SYD(悉尼金斯福德·史密斯机场) -> MNL(马尼拉尼诺伊·阿基诺国际机场) -> PVG(上海浦东国际机场)",
          segments: [
            {
              route: "SYD(悉尼金斯福德·史密斯机场) -> MNL(马尼拉尼诺伊·阿基诺国际机场)",
              flight_number: "5J40",
              airline: "Cebu Pacific",
              airline_zh: "宿务太平洋航空",
              aircraft: "Airbus A330-900neo",
              aircraft_zh: "空客 A330-900neo",
              origin_airport: "SYD",
              origin_airport_name_zh: "悉尼金斯福德·史密斯机场",
              departure_time: "2026-10-07T12:15:00",
              destination_airport: "MNL",
              destination_airport_name_zh: "马尼拉尼诺伊·阿基诺国际机场",
              arrival_time: "2026-10-07T17:50:00",
            },
            {
              route: "MNL(马尼拉尼诺伊·阿基诺国际机场) -> PVG(上海浦东国际机场)",
              flight_number: "5J678",
              airline: "Cebu Pacific",
              airline_zh: "宿务太平洋航空",
              aircraft: "Airbus A321neo",
              aircraft_zh: "空客 A321neo",
              origin_airport: "MNL",
              origin_airport_name_zh: "马尼拉尼诺伊·阿基诺国际机场",
              departure_time: "2026-10-07T20:20:00",
              destination_airport: "PVG",
              destination_airport_name_zh: "上海浦东国际机场",
              arrival_time: "2026-10-08T00:05:00",
            },
          ],
          segment_summaries: [],
          stop_count: 1,
          layovers: [{ airport: "MNL", airport_name_zh: "马尼拉尼诺伊·阿基诺国际机场", duration_hours: 2.5 }],
          stop_layover_summary: "1 次中转；MNL(马尼拉尼诺伊·阿基诺国际机场) 停留 2.5 小时",
          price_cny: 3960,
          airlines: ["宿务太平洋航空"],
          departure_time: "2026-10-07T12:15:00",
          arrival_time: "2026-10-08T00:05:00",
          origin_airport: "SYD",
          destination_airport: "PVG",
          layover_hours_total: 2.5,
          layover_cities: ["MNL(马尼拉尼诺伊·阿基诺国际机场)"],
        },
        purchase_links: {
          outbound: { type: "booking", label: "购买页", url: "https://www.google.com/travel/flights/booking?tfu=mock-outbound" },
          inbound: { type: "booking", label: "购买页", url: "https://www.google.com/travel/flights/booking?tfu=mock-inbound" },
        },
      },
      {
        rank: 2,
        total_price_cny: 7898,
        outbound: {
          itinerary: "PVG(上海浦东国际机场) -> KUL(吉隆坡国际机场) -> SYD(悉尼金斯福德·史密斯机场)",
          segments: [
            {
              route: "PVG(上海浦东国际机场) -> KUL(吉隆坡国际机场)",
              flight_number: "OD617",
              airline: "Malindo Airways",
              airline_zh: "马印航空",
              aircraft: "Boeing 737",
              aircraft_zh: "波音 737",
              origin_airport: "PVG",
              origin_airport_name_zh: "上海浦东国际机场",
              departure_time: "2026-09-29T02:20:00",
              destination_airport: "KUL",
              destination_airport_name_zh: "吉隆坡国际机场",
              arrival_time: "2026-09-29T08:00:00",
            },
            {
              route: "KUL(吉隆坡国际机场) -> SYD(悉尼金斯福德·史密斯机场)",
              flight_number: "OD119",
              airline: "Malindo Airways",
              airline_zh: "马印航空",
              aircraft: "Airbus A330",
              aircraft_zh: "空客 A330",
              origin_airport: "KUL",
              origin_airport_name_zh: "吉隆坡国际机场",
              departure_time: "2026-09-29T09:40:00",
              destination_airport: "SYD",
              destination_airport_name_zh: "悉尼金斯福德·史密斯机场",
              arrival_time: "2026-09-29T20:00:00",
            },
          ],
          segment_summaries: [],
          stop_count: 1,
          layovers: [{ airport: "KUL", airport_name_zh: "吉隆坡国际机场", duration_hours: 1.7 }],
          stop_layover_summary: "1 次中转；KUL(吉隆坡国际机场) 停留 1.7 小时",
          price_cny: 3938,
          airlines: ["马印航空"],
          departure_time: "2026-09-29T02:20:00",
          arrival_time: "2026-09-29T20:00:00",
          origin_airport: "PVG",
          destination_airport: "SYD",
          layover_hours_total: 1.7,
          layover_cities: ["KUL(吉隆坡国际机场)"],
        },
        inbound: {
          itinerary: "SYD(悉尼金斯福德·史密斯机场) -> MNL(马尼拉尼诺伊·阿基诺国际机场) -> PVG(上海浦东国际机场)",
          segments: [
            {
              route: "SYD(悉尼金斯福德·史密斯机场) -> MNL(马尼拉尼诺伊·阿基诺国际机场)",
              flight_number: "5J40",
              airline: "Cebu Pacific",
              airline_zh: "宿务太平洋航空",
              aircraft: "Airbus A330-900neo",
              aircraft_zh: "空客 A330-900neo",
              origin_airport: "SYD",
              origin_airport_name_zh: "悉尼金斯福德·史密斯机场",
              departure_time: "2026-10-07T12:15:00",
              destination_airport: "MNL",
              destination_airport_name_zh: "马尼拉尼诺伊·阿基诺国际机场",
              arrival_time: "2026-10-07T17:50:00",
            },
            {
              route: "MNL(马尼拉尼诺伊·阿基诺国际机场) -> PVG(上海浦东国际机场)",
              flight_number: "5J678",
              airline: "Cebu Pacific",
              airline_zh: "宿务太平洋航空",
              aircraft: "Airbus A321neo",
              aircraft_zh: "空客 A321neo",
              origin_airport: "MNL",
              origin_airport_name_zh: "马尼拉尼诺伊·阿基诺国际机场",
              departure_time: "2026-10-07T20:20:00",
              destination_airport: "PVG",
              destination_airport_name_zh: "上海浦东国际机场",
              arrival_time: "2026-10-08T00:05:00",
            },
          ],
          segment_summaries: [],
          stop_count: 1,
          layovers: [{ airport: "MNL", airport_name_zh: "马尼拉尼诺伊·阿基诺国际机场", duration_hours: 2.5 }],
          stop_layover_summary: "1 次中转；MNL(马尼拉尼诺伊·阿基诺国际机场) 停留 2.5 小时",
          price_cny: 3960,
          airlines: ["宿务太平洋航空"],
          departure_time: "2026-10-07T12:15:00",
          arrival_time: "2026-10-08T00:05:00",
          origin_airport: "SYD",
          destination_airport: "PVG",
          layover_hours_total: 2.5,
          layover_cities: ["MNL(马尼拉尼诺伊·阿基诺国际机场)"],
        },
        purchase_links: {
          outbound: { type: "search", label: "搜索页链接", url: "https://www.google.com/travel/flights?q=PVG%20SYD" },
          inbound: { type: "booking", label: "购买页", url: "https://www.google.com/travel/flights/booking?tfu=mock-inbound-2" },
        },
      },
    ],
  },
  network_status: {
    status: "ok",
    proxy: { has_proxy: false, https_proxy: null, all_proxy: null },
    checks: [
      { name: "fli_cli", status: "ok", ok: true, message: "找到 fli CLI" },
      { name: "google_flights", status: "ok", ok: true, message: "Google Flights 可访问，HTTP 200", latency_ms: 380 },
    ],
  },
  provider_status: {
    provider: "mock",
    status: "ok",
    result_count: 2,
    warnings: [],
    categories: [],
    message: null,
  },
  error: null,
};
